# Generated by Django 4.2.4 on 2023-10-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_productmodel_cat_productmodel_sub_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='img2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='img3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='img4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
