# Generated by Django 4.2.4 on 2023-10-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_productmodel_img2_alter_productmodel_img3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
