# Generated by Django 4.2.4 on 2023-10-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_productmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
