# Generated by Django 4.2.4 on 2023-10-08 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_productmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
